name: Basic workflow

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - run: npm run test
  codequality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run eslint
